---
- name: Gather package facts
  hosts: all
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Gather package facts
      apt:
        list: yes
      register: package_facts

    - name: Identify packages with updates
      debug:
        var: item
      loop: "{{ package_facts.packages }}"
      when: item.version != item.latest_version
